# permissions for end users to view hostconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostconfig-viewer-role
rules:
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - hostconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - hostconfigs/status
  verbs:
  - get
