# permissions for end users to edit hoststates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hoststate-editor-role
rules:
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - hoststates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - hoststates/status
  verbs:
  - get
