apiVersion: plumber.k8s.pf9.io/v1
kind: HostConfig
metadata:
  name: hostconfig-kernel-enp3
spec:
  # Add fields here
  sriovConfig:
    - pfName: enp3s0f1
      numVfs: 8
      vfDriver: vfio-pci
      mtu: 1500
    - pfName: enp3s0f0
      numVfs: 8
      vfDriver: ixgbevf
