apiVersion: plumber.k8s.pf9.io/v1
kind: HostNetworkTemplate
metadata:
  name: hostconfig-kernel-enp3
spec:
  # Add fields here
  sriovConfig:
    - pfName: enp3s0f1
      numVfs: 4
      vfDriver: vfio-pci
      mtu: 9000
    - pfName: enp3s0f0
      numVfs: 4
      vfDriver: ixgbevf
