apiVersion: plumber.k8s.pf9.io/v1
kind: NetworkPlugins
metadata:
  name: networkplugins-sample11
spec:
  # Add fields here
  plugins:
    hostPlumber:
      hostPlumberImage: "xagent003/luigi-plumber:latest"
    #nodeFeatureDiscovery: {}
    multus: {}
    whereabouts:
      whereaboutsImage: "platform9/whereabouts:latest"
    #sriov: {}
